### PR TITLE
Create LICENCE.MD

### PR DESCRIPTION
**Pull request by joereddington**
As per offline conversation.

### CODE REVIEW

**Comment by psi77** [comment]
Do we want some kind of copyright notice in a footer somewhere? Maybe on the bottom of the config page?

**Comment by blaise17** [comment]
I think we have to to be under this license:

> An interactive user interface displays "Appropriate Legal Notices" to
the extent that it includes a convenient and prominently visible
feature that (1) displays an appropriate copyright notice, and (2)
tells the user that there is no warranty for the work (except to the
extent that warranties are provided), that licensees may convey the
work under this License, and how to view a copy of this License.

**Comment by blaise17** [comment]
I think we also need to add the copyright and license notice to the top of each of our source files:

> If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these
terms.
 To do so, attach the following notices to the program. It is safest to
attach them to the start of each source file to most effectively state
the exclusion of warranty; and each file should have at least the
"copyright" line and a pointer to where the full notice is found.
         <one line to give the program's name and a brief idea of what it does.>
        Copyright (C) <year>  <name of author>
         This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.
         This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.
         You should have received a copy of the GNU General Public License
        along with this program.  If not, see <https://www.gnu.org/licenses/>.

**Comment by joereddington-public** [comment]
Some notes from updating changes. 

[This page](https://www.gnu.org/licenses/gpl-howto.en.html) wants the licence in a COPYING file rather than licence.md. I feel like licence.md is better understood on Github and other places so I'm inclinded to leave it as licence.md - [this stackoverflow](https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project) goes thought some of the details. 

I'm using this text as the boilerplate:

> 
>     This file is part of OVFPlayer.
>     OVFPlayer is free software: you can redistribute it and/or modify
>     it under the terms of the GNU General Public License as published by
>     the Free Software Foundation, either version 3 of the License, or
>     (at your option) any later version.
> 
>     OVFPlayer is distributed in the hope that it will be useful,
>     but WITHOUT ANY WARRANTY; without even the implied warranty of
>     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>     GNU General Public License for more details.
> 
>     You should have received a copy of the GNU General Public License
>     along with OVFPlayer.  If not, see <https://www.gnu.org/licenses/>.

I've left multiple commits in this pull because [I understand we can sqash and merge](https://help.github.com/articles/about-pull-request-merges/) after the fact.

I'm assuming that we only put the notice in files that we've created or changed.  

Here are the files we have at the moment: 

```
Josephs-Mini:ovfplayer joepublic$ find . | grep .js$ | wc
       4       4     138
Josephs-Mini:ovfplayer joepublic$ find . | grep .ts$ | wc
      55      55    1802
Josephs-Mini:ovfplayer joepublic$ find . | grep .html$ | wc
       8       8     328
Josephs-Mini:ovfplayer joepublic$ find . | grep .css$ | wc
       8       8     321
Josephs-Mini:ovfplayer joepublic$ 
```

Assumptions made: 
* That we don't put the notice on unaltered automatically generated files 
* That css files were commited once in their unaltered state. 
* That all ts files have been changed or will be. 

All the html files except one turned out to be modified and I have added the notice to them.

Smoke test done: looks like this: 

screen shot 2018-12-10 at 10 46 13

**Pull request closed without merging**
