### PR TITLE
Give a helpful error if root board is not valid

### PR DESCRIPTION
**Pull request by psi77**

### CODE REVIEW

**Comment by joereddington** [comment]
Testing using the file from #92 (which I think is what the PR is focused on). I'm afraid I don't get an error message at all.  The system halts at 'caching' :(  

File is at: https://joereddington.github.io/testobz/pagesetp.obz

**Comment by psi77** [comment]
Are you definitely testing it on the correct branch, not develop?

**Comment by psi77** [comment]
I get this if I try and use your link

**Comment by psi77** [comment]
@joereddington what browser are you using?  If you open up the debug console (F12 in chrome and firefox) do you get any errors reporting in there?

**Comment by joereddington** [comment]
Okay, full information: 

I'm running the code this way: 

```
joereddington@joereddington-MacBookAir:~/ovfplayer$ git status
On branch simon/issue#92/invalid_root
Your branch is up-to-date with 'origin/simon/issue#92/invalid_root'.

nothing to commit, working tree clean
joereddington@joereddington-MacBookAir:~/ovfplayer$ git log | head
commit 6615d02bc2cb8921fbbd50014a07a33e9eaa8233
Author: psi77 <simon@smith77.co.uk>
Date:   Wed Jan 30 10:47:39 2019 +0000

    Fix test after merge from develop

commit bf3c4b505b49efc65f6055a63e83b7874fc39358
Merge: aef3865 100f023
Author: Simon <simon@smith77.co.uk>
Date:   Wed Jan 30 10:33:04 2019 +0000
joereddington@joereddington-MacBookAir:~/ovfplayer$ npm start

> open-voice-factory@0.0.0 start /home/joereddington/ovfplayer
> ng serve

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                         p
Date: 2019-01-30T18:43:53.998Z
Hash: 197ae6c05be382fd4641
Time: 20981ms
chunk {main} main.js, main.js.map (main) 202 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 240 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 139 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.42 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

```

Which I think(?) shows that it's on the right branch. 

I'm running Firefox on Ubuntu and I'm getting this: 



With this log: 

```
Angular is running in the development mode. Call enableProdMode() to enable the production mode. core.js:16819
BoardCacheService: Cache is empty board-cache.service.ts:72:4
ObzService: Loading  https://joereddington.github.io/testobz/pagesetp.obz from internet obz.service.ts:225:4
ObzService: Parsed url pagesetp.obz obz.service.ts:225:4
Error: "Failed to download file  https://joereddington.github.io/testobz/pagesetp.obz: Could not parse  https://joereddington.github.io/testobz/pagesetp.obz as a zip file"
	OpenVoiceFactoryError http://localhost:4200/main.js:1454:21
	FatalOpenVoiceFactoryError http://localhost:4200/main.js:1466:21
	loadOBZFile http://localhost:4200/main.js:2358:298
	error http://localhost:4200/vendor.js:160018:26
	_error http://localhost:4200/vendor.js:156757:9
	error http://localhost:4200/vendor.js:156737:13
	notifyError http://localhost:4200/vendor.js:156247:9
	_error http://localhost:4200/vendor.js:155953:9
	error http://localhost:4200/vendor.js:156737:13
	notifyError http://localhost:4200/vendor.js:156247:9
	_error http://localhost:4200/vendor.js:155953:9
	error http://localhost:4200/vendor.js:156737:13
	throwError http://localhost:4200/vendor.js:158937:106
	_trySubscribe http://localhost:4200/vendor.js:156112:20
	subscribe http://localhost:4200/vendor.js:156098:17
	subscribeTo http://localhost:4200/vendor.js:167363:24
	subscribeToResult http://localhost:4200/vendor.js:167540:12
	error http://localhost:4200/vendor.js:160027:13
	subscribeToPromise http://localhost:4200/vendor.js:167508:36
	invoke http://localhost:4200/polyfills.js:2713:17
	onInvoke http://localhost:4200/vendor.js:74359:24
	invoke http://localhost:4200/polyfills.js:2712:37
	run http://localhost:4200/polyfills.js:2472:24
	scheduleResolveOrReject http://localhost:4200/polyfills.js:3211:29
	invokeTask http://localhost:4200/polyfills.js:2745:17
	onInvokeTask http://localhost:4200/vendor.js:74350:24
	invokeTask http://localhost:4200/polyfills.js:2744:41
	runTask http://localhost:4200/polyfills.js:2517:28
	drainMicroTaskQueue http://localhost:4200/polyfills.js:2923:25
global-error-handler.service.ts:30:4
Error on page /main: Failed to download file  https://joereddington.github.io/testobz/pagesetp.obz: Could not parse  https://joereddington.github.io/testobz/pagesetp.obz as a zip file global-error-handler.service.ts:

```
​
Does that help? I hope that helps...

**Comment by joereddington** [comment]
screenshot from 2019-01-30 18-45-53
(screenshot refused to upload in last comment)

**Comment by psi77** [comment]
Thanks for the info @joereddington , I think it's proper fixed now! Any chance you could retest please? I'd like to be sure this is working for everyone before merging it

**Comment by psi77** [comment]
Woo! Thank you!

**Pull request merged**
